version: '3.8'

services:
  # --- SERVICIO DEL BACKEND ---
  backend:
    build: ./backend
    container_name: oceans-api
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=3000
    networks:
      - oceans-network

  # --- SERVICIO DEL FRONTEND ---
  frontend:
    build: ./frontend
    container_name: oceans-app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - oceans-network

networks:
  oceans-network:
    driver: bridge